version: 2
jobs:
  test:
    docker:
      - image: node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: |
          npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
  deploy:
    docker:
      - image: ubuntu:17.10
    working_directory: ~/repo
    steps:
      - run:
          name: Setup
          command: |
            apt update
            apt --yes install \
              jq \
              git
      - checkout
      - run:
          name: tag version if it doesn't exist
          command: |
            echo ${CARDASHBOT_PRIVATE_KEY_BASE64_ENCODED} | base64 --decode > ~/repo/cardashbot.private
            chmod 400 ~/repo/cardashbot.private
            ssh-add -D
            ssh-add ~/repo/cardashbot.private
            ssh -o StrictHostKeyChecking=no git@github.com || true
            tag="v$(cat package.json | jq -r .version)"
            is_missing_tag=$(git tag | grep "^$tag$" || true | wc -l)

            if [[ $is_missing_tag ]]; then
              git tag $tag
              git push origin --tags
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
